// stubs/inertia-svelte/resources/js/Layouts/GuestLayout.svelte
<script>
    import { Link } from '@inertiajs/svelte'
    import ApplicationLogo from '@auth/Components/ApplicationLogo.svelte'
</script>

<div class="flex min-h-screen flex-col items-center bg-gray-100 pt-6 sm:justify-center sm:pt-0 dark:bg-gray-900">
    <div>
        <Link href="/">
            <ApplicationLogo class="h-20 w-20 fill-current text-gray-500" />
        </Link>
    </div>

    <div class="mt-6 w-full overflow-hidden bg-white px-6 py-4 shadow-md sm:max-w-md sm:rounded-lg dark:bg-gray-800">
        <slot />
    </div>
</div>

// stubs/inertia-react/resources/js/Layouts/GuestLayout.jsx
import ApplicationLogo from '@auth/Components/ApplicationLogo';
import { Link } from '@inertiajs/react';

export default function GuestLayout({ children }) {
    return (
        <div className="flex min-h-screen flex-col items-center bg-gray-100 pt-6 sm:justify-center sm:pt-0 dark:bg-gray-900">
            <div>
                <Link href="/">
                    <ApplicationLogo className="h-20 w-20 fill-current text-gray-500" />
                </Link>
            </div>

            <div className="mt-6 w-full overflow-hidden bg-white px-6 py-4 shadow-md sm:max-w-md sm:rounded-lg dark:bg-gray-800">
                {children}
            </div>
        </div>
    );
}
