// stubs/inertia-svelte/resources/js/Pages/Auth/ConfirmPassword.svelte
<script>
    import GuestLayout from '@auth/Layouts/GuestLayout.svelte'
    import InputError from '@auth/Components/InputError.svelte'
    import InputLabel from '@auth/Components/InputLabel.svelte'
    import PrimaryButton from '@auth/Components/PrimaryButton.svelte'
    import TextInput from '@auth/Components/TextInput.svelte'
    import { useForm } from '@inertiajs/svelte'

    const form = useForm({
        password: '',
    })

    function submit(e) {
        e.preventDefault()

        $form.post(route('password.confirm'), {
            onFinish: () => $form.reset(),
        })
    }
</script>

<svelte:head>
    <title>Confirm Password</title>
</svelte:head>

<GuestLayout>
    <div class="mb-4 text-sm text-gray-600 dark:text-gray-400">
        This is a secure area of the application. Please confirm your password before continuing.
    </div>

    <form onsubmit={submit}>
        <div>
            <InputLabel for="password" value="Password" />
            <TextInput
                id="password"
                type="password"
                class="mt-1 block w-full"
                bind:value={$form.password}
                required
                autocomplete="current-password"
                autofocus
            />
            <InputError class="mt-2" message={$form.errors.password} />
        </div>

        <div class="mt-4 flex justify-end">
            <PrimaryButton class="ms-4 {$form.processing && 'opacity-25'}" disabled={$form.processing}
                >Confirm</PrimaryButton
            >
        </div>
    </form>
</GuestLayout>

// stubs/inertia-vue-ts/resources/js/Pages/Auth/ConfirmPassword.vue
<script setup lang="ts">
import GuestLayout from '@auth/Layouts/GuestLayout.vue';
import InputError from '@auth/Components/InputError.vue';
import InputLabel from '@auth/Components/InputLabel.vue';
import PrimaryButton from '@auth/Components/PrimaryButton.vue';
import TextInput from '@auth/Components/TextInput.vue';
import { Head, useForm } from '@inertiajs/vue3';

const form = useForm({
    password: '',
});

const submit = () => {
    form.post(route('password.confirm'), {
        onFinish: () => {
            form.reset();
        },
    });
};
</script>

<template>
    <GuestLayout>
        <Head title="Confirm Password" />

        <div class="mb-4 text-sm text-gray-600 dark:text-gray-400">
            This is a secure area of the application. Please confirm your
            password before continuing.
        </div>

        <form @submit.prevent="submit">
            <div>
                <InputLabel for="password" value="Password" />
                <TextInput
                    id="password"
                    type="password"
                    class="mt-1 block w-full"
                    v-model="form.password"
                    required
                    autocomplete="current-password"
                    autofocus
                />
                <InputError class="mt-2" :message="form.errors.password" />
            </div>

            <div class="mt-4 flex justify-end">
                <PrimaryButton
                    class="ms-4"
                    :class="{ 'opacity-25': form.processing }"
                    :disabled="form.processing"
                >
                    Confirm
                </PrimaryButton>
            </div>
        </form>
    </GuestLayout>
</template>
